version: '3'
services:
    # application
    webapi:
        build: ../desu-noto-api
        ports: 
            - "8080:80"
        depends_on: 
            - mongo
            - db
    
    # command database
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: desuroot
            MONGO_INITDB_ROOT_PASSWORD: 123123
        volumes:
            - mongo-data:/data/db
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 17017:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: desuroot
            ME_CONFIG_MONGODB_ADMINPASSWORD: 123123

    # query database
    db:
        image: mysql:8.0.21
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: desunotodb
            MYSQL_USER: dsuser
            MYSQL_PASSWORD: 123123
            MYSQL_ROOT_PASSWORD: admin123123
        ports:
            - 3306:3306
        volumes:
            - mysql-data:/var/lib/mysql
    adminer:
        image: adminer
        restart: always
        ports: 
            - 13306:8080

    # messaging system
    akhq:
        image: tchiotludo/akhq
        environment:
            AKHQ_CONFIGURATION: | 
                akhq:
                    connections:
                        docker-kafka-server:
                            properties:
                                bootstrap.servers: "kafka:9092"
               
        ports:
            - 19091:8080
        links:
            - kafka
    zookeeper:
        image: confluentinc/cp-zookeeper
        volumes:
            - zookeeper-data:/var/lib/zookeeper/data
            - zookeeper-log:/var/lib/zookeeper/log
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
    kafka:
        image: confluentinc/cp-kafka
        volumes:
            - kafka-data:/var/lib/kafka
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_NUM_PARTITIONS: 12
            KAFKA_COMPRESSION_TYPE: gzip
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
            KAFKA_JMX_PORT: 9091
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
        links:
            - zookeeper

volumes:
    mongo-data:
    mysql-data:
    zookeeper-data:
    zookeeper-log:
    kafka-data: