version: '3'
services:
    webapi:
        build: ../desu-noto-api
        ports: 
            - "8080:80"
        depends_on: 
            - mongo
    mongo:
        image: mongo
        restart: always
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: desuroot
            MONGO_INITDB_ROOT_PASSWORD: 123123
        volumes:
            - mongo-data:/data/db
    
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: desuroot
            ME_CONFIG_MONGODB_ADMINPASSWORD: 123123

volumes:
    mongo-data: